version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/gamgyul-code-server/
file_exists_behavior: OVERWRITE

permissions:
    - object: /
      pattern: '**'
      owner: root
      group: root

hooks:
    AfterInstall:
        - location: scripts/after-deploy.sh
          timeout: 2000
          runas: root
