spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://halmang.cn0ucog6cinm.ap-northeast-2.rds.amazonaws.com:3306/halmang
    username: root
    password: ${DEV_MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://43.200.126.36:8080/login/oauth2/code/google # 추우 백엔드 도메인 연결 시 수정
          naver:
            redirect-uri: http://43.200.126.36:8080/login/oauth2/code/naver
          kakao:
            redirect-uri: http://43.200.126.36:8080/login/oauth2/code/kakao

server:
  port: 8080

oauth2:
  success:
    redirect-url: http://43.200.126.36:8080/members/test2 # 추후 프론트 도메인 연결 시 수정