spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://halmang.cn0ucog6cinm.ap-northeast-2.rds.amazonaws.com:3306/halmang
    username: root
    password: halmangsql
